name: Build code and javadoc

on: push

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: 21
    - name: setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: build code and javadoc
      run: ./gradlew clean build javadoc
