name: Build code

on: push

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
